### ISSUE TITLE
Support for webpack 4

### ISSUE THREAD

**Issue by thisjunewest** [jalkoby/sass-webpack-plugin#13]
Can you please add support for webpack 4?

Currently fails in development mode with the error:

```
DeprecationWarning: Tapable.plugin is deprecated.
...
sass-webpack-plugin/index.js:18
  if (list.indexOf(item) === -1) list.push(item);
           ^

TypeError: list.indexOf is not a function
```

**Comment by jalkoby** [comment]
Hi. thanks for submitting the issue. will take a look a little bit later.

**Comment by chrisschaetzlein** [comment]
+1 me on this. Ran into the same issue.

**Comment by chrisschaetzlein** [comment]
@tino415 's fork seems to do the trick for me:
https://github.com/tino415/sass-webpack-plugin/commit/c93b622da84abf28fb354812938aebfb514de425

Could you apply these changes and publish a new package to npm?

**Comment by jalkoby** [comment]
Chris, please make a polyfill for both versions (3 - as array & 4 - as set)

**Comment by jalkoby** [comment]
Also I didn't have time to figure out how to force webpack 4+ to push changes, when a plugin file was changed
