### ISSUE TITLE
Error in last update

### ISSUE THREAD

**Issue by tbigueres** [jalkoby/sass-webpack-plugin#15]
Hi, 

I've tried to add the sass plugin which looks way better than loader for my case. 
Though I have a problem, when I install it through :  
`npm i -D webpack webpack-dev-server sass-webpack-plugin html-webpack-plugin html-webpack-template`
The folder that is created in my node_modules contains a src folder. I think the src folder should be the root folder. 
![image](https://user-images.githubusercontent.com/2139076/42231093-ea5a0b3e-7eea-11e8-947f-078a25961bbd.png)

Because of this (I think) I have an issue when trying to do npm run start : 

![image](https://user-images.githubusercontent.com/2139076/42231127-05b03d18-7eeb-11e8-98a0-1e68f6802ec0.png)

Is there something we can do to change that ? 

Thanks you. 
Thoma

**Comment by tbigueres** [comment]
FYI : 
I had to go in the folder
do npm install 
do npm build
move file from dist to root

and it seems to work.

**Comment by jalkoby** [comment]
ohh, yes - I've published it in a wrong way - 1.0.3 welcome

**Comment by tbigueres** [comment]
Thanks :)
