### ISSUE TITLE
Allow all sass options

### ISSUE THREAD

**Issue by musicin3d** [jalkoby/sass-webpack-plugin#16]
I'm trying to change the name of the output file, but a quick look through the source code suggested that this plugin is filtering the sass configuration. Why would you do this? More importantly, could we be allowed to set the output file name?

**Comment by jalkoby** [comment]
https://github.com/jalkoby/sass-webpack-plugin#config-examples

```js
  new SassPlugin({ './src/styles/index.scss': 'bundle.css' }, process.env.NODE_ENV);
 ```
