### ISSUE TITLE
Is there a way to output the hash of the content in the filename?

### ISSUE THREAD

**Issue by thisjunewest** [jalkoby/sass-webpack-plugin#20]
Would like to be able to do caching in the same way as other webpack assets

**Comment by jalkoby** [comment]
```js
new SassPlugin({ './src/styles/index.scss': `bundle.${Date.now()}.css` }, process.env.NODE_ENV);
```

**Comment by thisjunewest** [comment]
Sorry, to be more clear, I would like to be able to use a hash of the file - which is a much more useful solution than a date, which changes each time you build.
