### ISSUE TITLE
multiple scss input files => multiple css output files

### ISSUE THREAD

**Issue by pedrotainha** [jalkoby/sass-webpack-plugin#3]
I would love to have this functionality.

I saw the source code but i don't understand well the lifecycle.

If this is quick to implement and you point me to the right way i may help. Thanks

**Comment by jalkoby** [comment]
It’s a thin layer between webpack and node-sass(which supports a single file mod), so getting a multiple inputs should be done by plugin internally. At that time you can have a multiple inputs by including an instance of the plugin for each root file

**Comment by pedrotainha** [comment]
I was able to do it, by passing a list of files to the plugin. I prefer that approach instead of passing multiple plugins (more plugins means more initial load boostrap plugin). To work i had to remove the "Audit" part and the tests. I didn't understand well the propose of the Audit...

**Comment by jalkoby** [comment]
Audit is used to prevent compilation each time the processing is done(dev server mode)

**Comment by jalkoby** [comment]
@pedrotainha please install v1.0.0 and take a look here https://github.com/jalkoby/sass-webpack-plugin#config-examples
