### ISSUE TITLE
Integrate with caching solution

### ISSUE THREAD

**Issue by ajhsu** [jalkoby/sass-webpack-plugin#6]
Hi @jalkoby ,
Thanks for making the awesome plugin!

Meanwhile, I got a problem that when we want to compile assets from source files into production files, we would compress files and naming these files with a hash, such as `style.cd1cb8.css`; Then outputs a mapping file called `manifest.json` to indicate which file should be replaced with a specific hashed file path. So that we can ensure these files will be updated and appropriately cached by browser with a unique filename.

But the [`[hash]` substitution mechanism](https://webpack.js.org/guides/caching/#output-filenames) that webpack built-in is only able to support those asset processing via loaders but not those files comes from plugins.

And that will cause a problem: I can't write my .css files into the `manifest.json`, which means I can't cache my stylesheet asset with hashed filenames.

Do we have any solution for this?

**Comment by jalkoby** [comment]
Hi. 

Thanks for submitting the issue. Yes, I had a thought about it, but didn't have time for that. Also this "hashing" part could be done without webpack like:

```js
const outStyleName = `index${process.env.NODE_ENV === 'production' ? Date.now().toString(16) : ''}.css`;

module.exports = {
    entry: './src/js/index.js',
    plugins: [
      new SassPlugin({ './src/styles/index.scss': outStyleName }, process.env.NODE_ENV),
      new HtmlPlugin({
        inject: false,
        template: require('html-webpack-template'),
        title: 'Sass webpack plugin',
        links: [{ rel: 'stylesheet', type: 'text/css', href: outStyleName }]
     })
   ]
}
```

**Comment by ajhsu** [comment]
Hi @jalkoby, thanks for the solution.
I think it's the most feasible solution so far and I'll try it in my project.
Thanks again for your help!
